services:
  app:
    image: blood-donation-app
    container_name: blood-donation-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # React
      - "8080:8080" # Spring Boot
      - "3306:3306" # MySQL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/bloodmanagementsystem
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bloodmanagementsystem
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - .:/workspace
      - ~/.gitconfig:/root/.gitconfig
    working_dir: /workspace
