CREATE DATABASE BloodManagementSystem;
USE BloodManagementSystem;

CREATE TABLE Users (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    City VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Admins (
    AdminID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE BloodGroups (
    BloodGroupID INT PRIMARY KEY AUTO_INCREMENT,
    BloodGroup VARCHAR(3) UNIQUE NOT NULL
);

CREATE TABLE BloodInventory (
    InventoryID INT PRIMARY KEY AUTO_INCREMENT,
    BloodGroupID INT NOT NULL,
    FOREIGN KEY (BloodGroupID) REFERENCES BloodGroups(BloodGroupID),
    City VARCHAR(255) NOT NULL,
    Quantity INT DEFAULT 0 NOT NULL,
    UNIQUE (BloodGroupID, City),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE BloodAppeals (
    AppealID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    AdminID INT DEFAULT NULL,
    FOREIGN KEY (AdminID) REFERENCES Admins(AdminID),
    BloodGroupID INT NOT NULL,
    FOREIGN KEY (BloodGroupID) REFERENCES BloodGroups(BloodGroupID),
    Location VARCHAR(255) NOT NULL,
    Quantity INT NOT NULL,
    Status ENUM('PENDING', 'APPROVED', 'REJECTED') DEFAULT 'PENDING',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE BloodDonationRequests (
    RequestID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    AdminID INT DEFAULT NULL,
    FOREIGN KEY (AdminID) REFERENCES Admins(AdminID),
    BloodGroupID INT NOT NULL,
    FOREIGN KEY (BloodGroupID) REFERENCES BloodGroups(BloodGroupID),
    Location VARCHAR(255) NOT NULL,
    Quantity INT NOT NULL,
    Status ENUM('PENDING', 'APPROVED', 'REJECTED') DEFAULT 'PENDING',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
